export const promise = {
  SIGNIN: 'SIGNIN',
  SIGNOUT: 'SIGNOUT',
  ADD_DESTINATION: 'ADD_DESTINATION',
  SAVE_PROFILE: 'SAVE_PROFILE'
};

export const data = {
  MY_DESTINATIONS: 'MY_DESTINATIONS_LIST',
  DEFAULTS: 'DEFAULTS_CHANGE',
  MY_PROFILE: 'MY_PROFILE_CHANGE'
};
