export const promise = {
  SIGNIN: 'SIGNIN',
  SIGNOUT: 'SIGNOUT',
  ADD_DESTINATION: 'ADD_DESTINATION',
};

export const data = {
  MY_DESTINATIONS: 'MY_DESTINATIONS_LIST',
  DEFAULT_DESTINATION: 'DEFAULT_DESTINATION_CHANGE',
  MY_PROFILE: 'MY_PROFILE_CHANGE'
};
